djangoinit/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [path("admin/", admin.site.urls), path("polls/", include("polls.urls"))]

djangoinit/polls/urls.py
from django.urls import path

from . import views

# app_name = "polls"
# urlpatterns = [
#     path("", views.index, name="index"),
#     path("create", views.create, name="create"),
#     path("store", views.store, name="store"),
#     path("<int:question_id>", views.show, name="show"),
#     path("<int:question_id>/edit", views.edit, name="edit"),
#     path("<int:question_id>/update", views.update, name="update"),
#     path("<int:question_id>/results", views.result, name="results"),
#     path("<int:question_id>/vote", views.vote, name="vote"),
#     path("<int:question_id>/destroy", views.destroy, name="destroy"),
# ]

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>", views.ShowView.as_view(), name="show"),
    path("<int:pk>/results", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

djangoinit/polls/models.py
from django.db.models import (
    Model,
    CharField,
    DateTimeField,
    IntegerField,
    ForeignKey,
    CASCADE,
)
from django.utils.timezone import now
from datetime import timedelta


class Question(Model):
    question_text = CharField(max_length=200)
    pub_date = DateTimeField("date published")

    def was_published_recently(self):
        return now() - timedelta(days=1) <= self.pub_date <= now()

    def __str__(self):
        return self.question_text


class Choice(Model):
    question = ForeignKey(Question, on_delete=CASCADE)
    choice_text = CharField(max_length=30)
    votes = IntegerField(default=0)

    def __str__(self):
        return self.choice_text

djangoinit/polls/views.py
from django.db.models import F, Count
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.utils.timezone import now

from .models import Question, Choice


# def index(request):
#     latest_questions_list = Question.objects.order_by("-pub_date")[:5]
#     template = loader.get_template("polls/index.html")
#     context = {
#         "latest_questions_list": latest_questions_list,
#     }
#     print(latest_questions_list)

#     return HttpResponse(template.render(context, request))


# def show(request, question_id):
#     print(question_id)
#     # for q in Question.objects.all():
#     #     if q.id == question_id:
#     try:
#         question = Question.objects.get(pk=question_id)
#         template = loader.get_template("polls/show.html")
#         context = {
#             "question": question,
#         }
#     except Question.DoesNotExist:
#         raise Http404(f"Question with id {question_id} not found")
#     return HttpResponse(template.render(context, request))
#     # return HttpResponse(q)
#     # return HttpResponse(
#     #     f"Wanna see an item? Sikeeeee!!! No item found for id {question_id}"
#     # )


def create(request):
    return HttpResponse("Wanna create an item... alright \n\n\n double sike!")


def store(request):
    return HttpResponse("Ain't you tired of the sikes?")


def edit(request, question_id):
    print(question_id)
    return HttpResponse(
        f"You could not live with you own failure. Where did that bring you? Back to me. Question Id: {question_id}"
    )


def update(request, question_id):
    print(question_id)
    return HttpResponse(
        f"Mr. yale, there's no need to both cuss and yell, one of them will suffice. Question Id: {question_id}"
    )


def destroy(request, question_id):
    print(question_id)
    return HttpResponse(
        f"Dread it, run from it, destiny arrives all the same! Question Id: {question_id}"
    )


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/show.html",
            {
                "question": question,
                "error_message": "No choice selected.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))


# def result(request, question_id):
#     # print(question_id)
#     # return HttpResponse(f"results for {question_id}")

#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "polls/results.html", {"question": question})


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_questions_list"

    def get_queryset(self):
        return (
            Question.objects.annotate(num_choices=Count("choice"))
            .filter(num_choices__gt=0)
            .filter(pub_date__lte=now())
            .order_by("-pub_date")[:10]
        )


class ShowView(generic.DetailView):
    # model = Question
    template_name = "polls/show.html"

    def get_queryset(self):
        return (
            Question.objects.annotate(num_choices=Count("choice"))
            .filter(num_choices__gt=0)
            .filter(pub_date__lte=now())
        )


class ResultsView(generic.DetailView):
    # model = Question
    template_name = "polls/results.html"

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=now())

djangoinit/polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">

<body>
{% if latest_questions_list %}
<ul>
{% for question in latest_questions_list %}
  <li><a href="{% url 'polls:show' question.id %}">{{ question.question_text }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>No polls available</p>
{% endif %}
</body>

djangoinit/polls/templates/polls/question_form.html
<form action="{% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %}
  <fieldset>
    <legend><h1>{{question.question_text}}</h1></legend>
    {% if error_message %} <p><strong>{{ error_message }}</strong></p> {% endif %}
    {%for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id}}">
    <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label> <br>
    {% endfor %}
  </fieldset>
  <input type="submit" value="Vote">
</form>

djangoinit/polls/templates/polls/results.html
{% load polls_tags %}

<h1>{{ question.question_text }}</h1>

{% if not question.choice_set.all|has_votes %}
<p>No vote</p>
{% endif %}

<ul>
{% for choice in question.choice_set.all %}
  <li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:show' question.id %}">Vote again?</a>

djangoinit/polls/templates/polls/show.html
<p>{{ question.question_text }}</p>
{% for choice in question.choice_set.all %}
<li> {{ choice.choice_text }} </li>
{% endfor %}